### PR TITLE
Fixed resolver to accept a data parameter

### PR DESCRIPTION
**Pull request by DanielMaly**
Seems to fix issue #9 but I haven't tested thoroughly.

### CODE REVIEW

**Comment by Alien1993** [comment]
The code looks good but you should write a test that reproduces issue #9 before I can merge.

**Comment by Alien1993** [comment]
I'm closing this PR since it doesn't respect [the guidelines of the project](https://mkm-sdk.readthedocs.io/en/latest/contributing.html#pull-request-guidelines). Every bug fix should come with the related test that reproduces the issue. 

It would be great also if every PR focuses on one thing. I can't merge a PR that fixes a bug and adds a new endpoint but I can merge two separate branches, one for the bug fix and one for the new endpoint. 

Feel free to submit a new PR whenever you want, obviously respecting the guidelines. :smile:

**Comment by DanielMaly** [comment]
This was a trivial fix and writing a test to reproduce the issue was entirely unnecessary, as the feature was simply missing. It fixes a glaring bug that makes many of the API methods unusable.

The later commits were added to the branch by mistake and honestly, by that time I'd given up on having the PR merged.

**Comment by Alien1993** [comment]
Hi @DanielMaly, I've cherry-picked your commit 2d28c17 and rebased it since your code is correct; you also appear as a contributor now.
I hope you appreciate that and will keep contributing in the future.

**Pull request closed without merging**
